import type { SurveyConfig } from '@/lib/types';

const PROCEDURES = [
  '보톡스',
  '필러',
  '피코레이저(토닝/프락셀)',
  '스킨부스터(리쥬란/쥬베룩)',
  '리프팅(울쎄라/써마지)',
  '슈링크/인모드',
  '레이저 제모',
  '여드름/흉터 치료',
  '실리프팅',
  '미백/색소 치료',
];

const PRICE_LEVELS = [
  { id: 'high', label: '매우높음' },
  { id: 'avg', label: '평균수준' },
  { id: 'low', label: '매우낮음' },
  { id: 'unk', label: '모름' },
];

export const viralConfig: SurveyConfig = {
  clinicName: '',
  brandName: '호원앤컴퍼니',
  surveyTitle: '바이럴 마케팅\n분석 사전 설문',
  formspreeId: 'xeollevk',
  thankYouMessage: '귀하의 소중한 응답에 감사드립니다.\n답변을 심도있게 검토하여 맞춤 컨설팅 방향을 안내드리겠습니다.',
  headerDescription: '분석에 앞서 귀 의료기관의 현황을 파악하기 위한 사전 설문입니다.\n모든 항목에 성실히 응답해 주시기 바랍니다.',
  subjectPrefix: '바이럴 마케팅 컨설팅 사전 설문',
  footerNotice: '본 설문의 모든 응답은 암호화되어 안전하게 전송되며,\n바이럴 마케팅 컨설팅 목적 외에는 사용되지 않습니다.',
  metaDescription: '호원앤컴퍼니 바이럴 마케팅 컨설팅 사전 설문',
  editionLabel: 'No. 026 · Medical Marketing Intake',
  mastheadSubtitle: 'For Dermatology Clinics',
  estimatedMinutes: 8,
  questions: [
    // Section A — 기본 정보
    {
      id: 'q01',
      section: 'A',
      sectionTitle: '기본 정보',
      label: '귀 의료기관의 정보를 확인합니다.',
      type: 'identity',
      required: true,
    },
    // Section B — 진료 포트폴리오
    {
      id: 'q02',
      section: 'B',
      sectionTitle: '진료 포트폴리오',
      label: '귀 의료기관의 주력 시술 및 진료 항목을 알려주세요.',
      type: 'textarea',
      hint: '예: 보톡스, 필러, 피코레이저, 리프팅, 스킨부스터, 제모 등',
      required: true,
      rows: 6,
    },
    {
      id: 'q03',
      section: 'B',
      sectionTitle: '진료 포트폴리오',
      label: '주요 타겟 고객층은 어떻게 되시나요?',
      type: 'textarea',
      hint: '연령대, 성별, 지역, 주요 내원 경로 등',
      required: true,
      rows: 4,
    },
    // Section C — 바이럴 현황
    {
      id: 'q04',
      section: 'C',
      sectionTitle: '바이럴 현황',
      label: '보유하고 계신 네이버 블로그 계정명이 어떻게 되시나요?',
      type: 'text',
      hint: '블로그 URL 또는 계정명을 적어주세요. 없으시면 ‘없음’이라고 적어주세요.',
      placeholder: '예: blog.naver.com/hospital-name',
      required: true,
    },
    {
      id: 'q05',
      section: 'C',
      sectionTitle: '바이럴 현황',
      label: '현재 운영 중인 SNS 계정이나 바이럴 채널의 URL을 알려주세요.',
      type: 'textarea',
      hint: '인스타그램, 유튜브, 네이버 블로그, 카카오 채널 등\n의료기관 계정인지 대행사 계정인지 분류해주시고, 월간 포스팅 건수도 알려주세요.',
      required: true,
      rows: 6,
    },
    {
      id: 'q06',
      section: 'C',
      sectionTitle: '바이럴 현황',
      label: '월간 콘텐츠 발행 빈도와 관리 주체를 알려주세요.',
      type: 'textarea',
      hint: '직접 관리 / 대행사 위탁 / 혼합, 월 몇 건 발행 등',
      required: false,
      rows: 4,
    },
    // Section D — 바이럴 목표
    {
      id: 'q07',
      section: 'D',
      sectionTitle: '바이럴 목표',
      label: '상위 노출을 원하는 키워드를 알려주세요.',
      type: 'textarea',
      hint: '예: 강남피부과, 여드름치료잘하는곳, 피코레이저후기 등 구체적으로 적어주세요.',
      required: true,
      rows: 6,
    },
    {
      id: 'q08',
      section: 'D',
      sectionTitle: '바이럴 목표',
      label: '이상적으로 여기시는 바이럴 광고 대상처(레퍼런스)가 있다면 알려주세요.',
      type: 'textarea',
      hint: '잘하고 있다고 생각하시는 경쟁 병원이나 블로그, 콘텐츠 등',
      required: false,
      rows: 4,
    },
    {
      id: 'q09',
      section: 'D',
      sectionTitle: '바이럴 목표',
      label: '현재 바이럴 마케팅에서 가장 어렵거나 불만족스러운 점은 무엇인가요?',
      type: 'textarea',
      hint: '예: 블로그 상위노출 어려움, 콘텐츠 품질, 대행사 커뮤니케이션, 비용 대비 효과 등',
      required: true,
      rows: 6,
    },
    // Section E — 경쟁 & 예산
    {
      id: 'q10',
      section: 'E',
      sectionTitle: '경쟁 & 예산',
      label: '생각하시는 경쟁 대상 병원은 주로 어떻게 되시나요?',
      type: 'textarea',
      hint: '답변 주신 내용을 제외하고 잠재 경쟁자의 분석이 추가 진행됩니다.',
      required: false,
      rows: 4,
    },
    {
      id: 'q11',
      section: 'E',
      sectionTitle: '경쟁 & 예산',
      label: '월간 마케팅 예산은 어떻게 되시나요?',
      type: 'text',
      hint: '바이럴, 광고, 대행사 비용 등 전체 마케팅 예산',
      placeholder: '예: 월 300만원',
      required: true,
    },
    {
      id: 'q12',
      section: 'E',
      sectionTitle: '경쟁 & 예산',
      label: '현재 마케팅 대행사를 이용하고 계신가요? 이용 중이라면 만족도는 어떠신가요?',
      type: 'textarea',
      required: false,
      rows: 4,
    },
    // Section F — 추가 분석
    {
      id: 'q13',
      section: 'F',
      sectionTitle: '추가 분석',
      label: '현재 운영 중인 광고 계정(네이버, 메타 등)의 수치나 설정을 직접 살펴볼 수 있다면 더욱 정밀한 분석과 전략 제안이 가능합니다. 혹시 조회 권한 부여가 가능한지 확인해 주세요.',
      type: 'textarea',
      hint: '어려우시다면 ‘불가’라고 적어주세요.',
      required: false,
      rows: 3,
    },
    {
      id: 'q14',
      section: 'F',
      sectionTitle: '추가 분석',
      label: '귀 의료기관의 시술 가격은 경쟁 의료기관 대비 어떤 수준인가요?',
      type: 'priceTable',
      hint: '특정 시술에서 가격 차이가 큰 항목이 있다면 적어주세요.',
      required: false,
      procedures: PROCEDURES,
      priceLevels: PRICE_LEVELS,
    },
  ],
};
